Kafka scripts
litmuschaos/test-tools pull request #171
Opened 2021-05-27 19:36 UTC by Adarshkumar14

**What this PR does / why we need it**:
Setup kafka-cluster on eks

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
 -  Kudo-based Kafka cluster which includes Kafka statefulset and zookeeper pods.
 -  It also Includes Prometheus and grafana.

**Special notes for your reviewer**:

2021-05-31 11:44 UTC, uditgaurav commented on custom/app-setup/kafka/ansible_kafka_cleanup.yml
> +- name: "[CleanUp]"
```suggestion
- name: "[CleanUp] Remove kafka cluster along with monitoring"
```

2021-05-31 11:45 UTC, uditgaurav commented on custom/app-setup/kafka/ansible_kafka_cleanup.yml
> +          - name: "[CleanUp: Removing Grafana deployment"
```suggestion
          - name: "[CleanUp]: Removing Grafana deployment"
```
Check for other tasks as well

2021-05-31 11:52 UTC, uditgaurav commented on custom/app-setup/kafka/README.md
> +          value: "eks"
Check for other ENVs like kafka version, os, arch.

2021-05-31 11:54 UTC, uditgaurav commented on custom/app-setup/kafka/roles/configure-exporter/.travis.yml
> +---
Do we need this file, if not we can remove it?

2021-05-31 11:56 UTC, uditgaurav commented on custom/app-setup/kafka/roles/configure-exporter/tasks/main.yml
> +                    cmd: kubectl label servicemonitor.monitoring.coreos.com kafka -n kafka  app=kafka-exporter --overwrite
Can we take namespace as an ENV?

2021-05-31 11:59 UTC, uditgaurav commented on custom/app-setup/kafka/roles/configure-kafka/tasks/main.yml
> +                url: https://github.com/kudobuilder/kudo/releases/download/v{{ VERSION }}/kubectl-kudo_{{ VERSION }}_{{ OS}}_{{ BIT_VERSION }}
```suggestion
                url: https://github.com/kudobuilder/kudo/releases/download/v{{ VERSION }}/kubectl-kudo_{{ VERSION }}_{{ OS}}_{{ ARCH }}
```

2021-06-10 11:57 UTC, uditgaurav requested changes

2021-06-10 11:57 UTC, uditgaurav commented on custom/app-setup/kafka/README.md
> +    <td> It defines the mode of experiment </td>
```suggestion
    <td> Provide <code>setup</code> to setup kafka cluster and <code>cleanup</code> for uninstallation </td>
```

2021-06-10 11:57 UTC, uditgaurav commented on custom/app-setup/kafka/README.md
> +    <td> It defines the platform of the k8s cluster </td>
```suggestion
    <td> provide the target platform  name. Like <code>eks</code></td>
```

2021-06-10 11:57 UTC, uditgaurav commented on custom/app-setup/kafka/README.md
> +    <td> The Kudo version to Install </td>
```suggestion
    <td> Provide the Kudo version for kafka Installation </td>
```

2021-06-10 11:57 UTC, uditgaurav commented on custom/app-setup/kafka/README.md
> + </table>
We can also take the namespace where we want to deploy kafka application as input.

2021-06-10 11:57 UTC, uditgaurav commented on custom/app-setup/kafka/ansible_kafka_cleanup.yml
> +                     kind: namespace
When we take Kafka namespace as an input variable then we have to pass that name everywhere as variable in place of hardcodding it as `kafka`

2021-06-10 11:57 UTC, uditgaurav commented on custom/app-setup/kafka/ansible_kafka_setup.yml
> +            import_role:
can we use 3 spaces only like we use in
```
  vars:    
     ansible_python_interpreter: /usr/bin/python3
```

2021-06-10 11:57 UTC, uditgaurav commented on custom/app-setup/kafka/roles/configure-exporter/tasks/main.yml
> +                  seconds: 5
need to check indentation everywhere once pls.

2021-06-11 15:27 UTC, uditgaurav commented on custom/app-setup/kafka/litmus-kafka-deployer/litmus-kafka-deployer-pod.yml
> +    image: aady12/demotest:latest
```suggestion
    image: litmuschaos/ansible-runner:latest
```

2021-06-11 15:27 UTC, uditgaurav commented on custom/app-setup/kafka/roles/configure-exporter/tasks/main.yml
> +                  var: monitor_log
```suggestion
- debug:
       var: monitor_log
```

2021-06-11 15:27 UTC, uditgaurav commented on custom/app-setup/kafka/roles/configure-kafka/tasks/main.yml
> +     wait_timeout: 100
```suggestion
     wait_timeout: 180
```

2021-06-11 15:27 UTC, uditgaurav commented on custom/app-setup/kafka/roles/configure-monitoring/tasks/main.yml
> +     force: true
can we use release branch

2021-06-11 15:27 UTC, uditgaurav commented on custom/app-setup/kafka/roles/configure-monitoring/tasks/main.yml
> +     seconds: 5
do we need this?

2021-06-12 11:18 UTC, ksatchit commented on custom/app-setup/kafka/roles/configure-kafka/vars/main.yml
> +---
can we take monitoring info/versions also here? We might also want to take litmus tunables (exporter version).

2021-06-17 11:52 UTC, uditgaurav commented on custom/app-setup/kafka/ansible_kafka_cleanup.yml
> +     - name: "[CleanUp]: Removing prometheus-k8s Statefulsets"
can we do a status check for termination?

2021-06-17 12:28 UTC, uditgaurav approved these changes

2021-06-17 18:05 UTC, uditgaurav approved these changes

2021-06-17 18:09 UTC, uditgaurav commented
We can also use the provisioned dashboard for grafana with the Kafka metrics. We can also add this is next PRs. @Adarshkumar14

2021-06-17 18:14 UTC, Adarshkumar14 commented
> We can also use the provisioned dashboard for grafana with the Kafka metrics. We can also add this is next PRs. @Adarshkumar14

2021-06-17 19:07 UTC, ispeakc0de commented on custom/app-setup/kafka/roles/configure-kafka/tasks/main.yml
> +- name: "[Wait]: Wait till the  object of zookeeper is not crerated"
```suggestion
- name: "[Wait]: Wait till the  object of zookeeper is not created"
```

2021-06-17 19:14 UTC, ispeakc0de approved these changes

2021-06-18 05:19 UTC, uditgaurav approved these changes

2021-06-18 05:21 UTC, merged