EKS setup using Terraform
litmuschaos/test-tools pull request #183
Opened 2021-07-08 09:00 UTC by Adarshkumar14

Setup EKS cluster with spot Instance using Terraform and configure Kafka.
- User have option to setup  only  eks cluster or User can also configure kafka along with prometheus and kafka provisioned grafana and litmus portal also.
-  User can delete  the whole resources that are created by Terraform using <code> terraform destroy</code>.

2021-07-12 09:14 UTC, uditgaurav commented on custom/scripts/eks/README.md
> +  git clone https://github.com/Adarshkumar14/kafka-eks-infra-setup.git
```suggestion
  git clone https://github.com/litmuschaos/test-tools.git
```

2021-07-12 09:27 UTC, oumkale commented on custom/scripts/eks/README.md
> +A terraform script to create a managed kubernetes cluster on AWS EKS with the spot Instance.This script also gives you an option to setup kafka along with prometheus and kafka-provisioned grafana and
A terraform script to create a managed Kubernetes cluster on AWS EKS with the Spot Instance. This script also gives you an option to set up Kafka along with Prometheus and Kafka-provisioned Grafana and also a litmus portal.

2021-07-12 09:28 UTC, oumkale commented on custom/scripts/eks/README.md
> +        <td><code>eks-vpc</code> </td>
Can you please crosscheck indentations?

2021-07-12 09:29 UTC, oumkale commented on custom/scripts/eks/README.md
> +  **Note:** If you are also configuring  kafka , then also you need to give the aws credentials in the secrets.For better understanding [refer this](https://github.com/litmuschaos/test-tools/tree/mas
```.For -> . For```

2021-07-12 09:30 UTC, oumkale commented on custom/scripts/eks/README.md
> + After Terraform has been successfully initialized, run <code>terraform apply</code>,It will ask for the setup of kafka ,enter <code>true</code> to setup else enter <code>false</code>.
Give proper spaces in words, ```, It```,  ```, enter```

2021-07-12 09:31 UTC, oumkale commented on custom/scripts/eks/litmus-kafka-deployer/litmus-kafka-deployer-pod.yml
> +        ##Supported values: setup, cleanup
Please can we have a proper and similar format for spaces?

2021-07-12 09:32 UTC, oumkale commented on custom/scripts/eks/main.tf
> +    //enable_irsa      = true
If this is not required then will you remove it?
Same for line nom 35, 36 etc.

2021-07-12 09:33 UTC, uditgaurav commented on custom/scripts/eks/README.md
> +      <th> Example </th>
```suggestion
      <th> Default </th>
```

2021-07-12 09:33 UTC, uditgaurav commented on custom/scripts/eks/README.md
> +    <td><code>eks-adarsh</code></td>
```suggestion
    <td><code>eks-litmus</code></td>
```

2021-07-12 09:33 UTC, uditgaurav commented on custom/scripts/eks/README.md
> +  aws eks --region aws_region_name update-kubeconfig --name eks_cluster_name
```suggestion
  aws eks --region <aws_region_name> update-kubeconfig --name <eks_cluster_name>
```

2021-07-12 09:33 UTC, uditgaurav commented on custom/scripts/eks/litmus-kafka-deployer/mysecret.yml
> +kind: Secret
Can we ask to add via REAMDE.md? we may not need to provide the manifest.

2021-07-12 09:33 UTC, uditgaurav commented on custom/scripts/eks/litmus-kafka-deployer/rbac.yml
> +metadata:
we can provide raw link in readme and re-use the older manifest for rbac

2021-07-12 09:33 UTC, uditgaurav commented on custom/scripts/eks/variables.tf
> +    default =  "eks-adarsh"
```suggestion
    default =  "eks-litmus"
```

2021-07-12 10:41 UTC, Jonsy13 requested changes

2021-07-12 10:41 UTC, Jonsy13 commented on custom/scripts/eks/README.md
> +   Provide the provider in providers.tf
Does the user needs this step? Also, why are we providing region here, same is provided through variables.tf.

2021-07-12 10:41 UTC, Jonsy13 commented on custom/scripts/eks/litmus-kafka-deployer/terraform.tfstate
> +{
Does the user needs this file, generally it contains the state of created infrastructure?

2021-07-12 10:41 UTC, Jonsy13 commented on custom/scripts/eks/README.md
> +```
Can we also add something about tags, the user can change the tags according to their preference. Otherwise, the default tags will be used.

2021-07-12 10:41 UTC, Jonsy13 commented on custom/scripts/eks/providers.tf
> +    region = "ap-south-1"
Can we take the region from variables?

2021-07-13 10:15 UTC, Jonsy13 commented on custom/scripts/eks/README.md
> +```
@Adarshkumar14 Can you add something here about tags, how users can change them. As it needs to be changed from main.tf. cc: @uditgaurav

2021-07-13 10:44 UTC, oumkale commented on custom/scripts/eks/README.md
> +Now Your eks-cluster is ready and configured.
Now your eks-cluster is ready and configured.

2021-07-13 10:45 UTC, oumkale commented on custom/scripts/eks/litmus-kafka-deployer-pod.yml
> +      ##Supported values: setup, cleanup
## Supported values: setup, cleanup

2021-09-25 07:28 UTC, ksatchit approved these changes

2021-09-25 07:28 UTC, merged