Adding redis helper for redis resiliency workflow
litmuschaos/test-tools pull request #203
Opened 2022-01-03 11:53 UTC by oumkale

Signed-off-by: Oum Kale <oumkale@chaosnative.com>

 - Adding redis helper for redis resiliency workflow
 - Redis Dashboard
 - Cmd probe checker
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2022-01-03 11:54 UTC, oumkale commented
![Screenshot from 2022-01-03 14-57-25](https://user-images.githubusercontent.com/34105373/147927531-6101f0f1-1c9a-48fc-881b-ec3e779e7344.png)
![Screenshot from 2022-01-03 14-57-29](https://user-images.githubusercontent.com/34105373/147927536-c49823a6-1015-4140-9641-d8352292e766.png)

2022-01-03 11:56 UTC, oumkale commented
![Screenshot from 2022-01-03 14-57-29](https://user-images.githubusercontent.com/34105373/147927715-563b4f18-0298-4240-81fb-0f7fccbf05e6.png)
![Screenshot from 2022-01-03 17-25-33](https://user-images.githubusercontent.com/34105373/147927717-e0a79741-ccbc-4a9b-a809-513d1ed45957.png)

2022-01-03 15:07 UTC, avaakash requested changes

2022-01-03 15:07 UTC, avaakash commented on custom/workflow-helper/redis-helper/load-gen/redisLoad.py
> +        self.client       = Client(host=host)
```suggestion
        self.client = Client(host=host)
```

2022-01-03 15:07 UTC, avaakash commented on custom/workflow-helper/redis-helper/load-gen/redis-cmd.py
> +        self.client       = Client(host=os.getenv("REDIS_HOST", "redis.redis.svc"))
```suggestion
        self.client = Client(host=os.getenv("REDIS_HOST", "redis.redis.svc"))
```

2022-01-04 11:32 UTC, avaakash approved these changes

2022-03-14 09:31 UTC, ksatchit approved these changes

2022-03-14 09:31 UTC, merged